### ISSUE TITLE
[not exactly a BUG]  I have not been able to use torch in the NAM environment

### ISSUE THREAD

**Issue by siberguy** [sdatkinson/neural-amp-modeler#173]
Apologies if this is not appropriate here.  When running nam I get:
[WinError 126] The specified module could not be found. Error loading "C:\Users\tabea\anaconda3\envs\nam\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.  I get the same if I just start python and import torch

I can start a clean environment and install torch (nvfuser ect) and get true for torch.cuda.is_available().  I used pip to install that and all the other packages referenced in environment_gpu.yml.   I can't run nam from there - maybe if I worked with it it would run?
 In the nam environment there seems to be a clash with some of the other packages. They are not exactly the same versions that install with pip.  I've considered specifying those in the nam environment but haven't yet.   My graphics card is RTX 2060 SUPER - up to date on drivers.   Windows 10, fresh anaconda install.  Any thoughts?
Thanks
Tim

**Comment by erikgrahn13** [comment]
Just wanted to say that I experience the same thing. I am not able to to run the nam environment due to the issue of loading anaconda3\envs\nam\lib\site-packages\torch\lib\nvfuser_codegen.dll.

**Comment by nmontua** [comment]
same problem here.

**Comment by sdatkinson** [comment]
The recommended way to use this is to configure your environment using Anaconda as described in [the README](https://github.com/sdatkinson/neural-amp-modeler#installation).

Does this not work?

**Comment by sdatkinson** [comment]
Hmm, I just noticed that you installed a version of PyTorch with CUDA version 11.8, not 11.7 as is [in the Anaconda environment](https://github.com/sdatkinson/neural-amp-modeler/blob/83886bd5ed8f8e6dabc99aeafcf2de5d2b2ec439/environment_gpu.yml#L21).

(1) Does the RTX3080 (assuming typo and not RTX380) not support CUDA 11.7?  (2) And, does modifying the Anaconda environment to use the right version of CUDA resolve the problem?

**Comment by nmontua** [comment]
Ampere architecture cards support CUDA 11.1 and later, so I do not think that was the issue (it is indeed an RTX3080, the 380 was a typo). I just chose the most current version of torch when I reinstalled. I don't think the CUDA version is the problem, as before reinstalling it, torch could not be loaded at all by "import torch" it in a python session.

**Comment by erikgrahn13** [comment]
I get this when trying to run nam. "conda activate nam" works but when trying to "nam" I get this

(nam) C:\Users\erikg\Development>nam
Traceback (most recent call last):
  File "C:\Users\erikg\anaconda3\envs\nam\Scripts\nam-script.py", line 33, in <module>
    sys.exit(load_entry_point('nam', 'console_scripts', 'nam')())
  File "C:\Users\erikg\anaconda3\envs\nam\Scripts\nam-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\erikg\anaconda3\envs\nam\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Users\erikg\anaconda3\envs\nam\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\users\erikg\development\neural-amp-modeler\nam\__init__.py", line 22, in <module>
    from . import data  # noqa F401
  File "c:\users\erikg\development\neural-amp-modeler\nam\data.py", line 14, in <module>
    import torch
  File "C:\Users\erikg\anaconda3\envs\nam\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\erikg\anaconda3\envs\nam\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

(nam) C:\Users\erikg\Development>

**Comment by sdatkinson** [comment]
Between the two, I'm going to continue to prioritize installation of the development environment via conda since ["Anaconda is our [PyTorch's] recommended package manager since it installs all dependencies."](https://pytorch.org/get-started/locally/). Supporting turn-key configuration for other package managers is going to be out of scope (except pip-based installation of the package from PyPI--which is explained in the local install videos ([Windows](https://www.youtube.com/watch?v=DFWVvJx1Cfs&lc=Ugx2zqyl0G8g6g9xBqR4AaABAg), [macOS](https://www.youtube.com/watch?v=8qyJvu9lKO8&lc=UgwThcye0qBUiFj4aRl4AaABAg))).

Otherwise, hopefully
```bash
conda env create -f environment_gpu.yml
```
works for you; if not; feel free to share the errors.

Closing this Issue since I don't see a problem that's in-scope that can be replicated.
