### ISSUE TITLE
Error while training on mac

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/neural-amp-modeler#211]
I get this when training to train on my M1 mac

Traceback (most recent call last):
  File "/Users/jonathan/miniconda/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/jonathan/miniconda/lib/python3.10/site-packages/nam/train/gui.py", line 287, in _train
    trained_model = core.train(
  File "/Users/jonathan/miniconda/lib/python3.10/site-packages/nam/train/core.py", line 377, in train
    input_version = _detect_input_version(input_path)
  File "/Users/jonathan/miniconda/lib/python3.10/site-packages/nam/train/core.py", line 50, in _detect_input_version
    raise RuntimeError(
RuntimeError: Provided input file /Users/jonathan/Downloads/v1_1_1.wav does not match any known standard input files.

**Comment by sdatkinson** [comment]
Try downloading [v1_1_1.wav](https://drive.google.com/file/d/1v2xFXeQ9W2Ks05XrqsMCs2viQcKPAwBk/view?usp=share_link) again?

**Comment by sdatkinson** [comment]
Closing bc no activity
