### ISSUE TITLE
[BUG] RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by sprack** [sdatkinson/neural-amp-modeler#223]
**Describe the bug**
Input tensors need to be sent to GPU device rather than CPU.

**To Reproduce**
1. Using just cli, no UI on hosts.
2. Run `python bin/train/main.py bin/train/inputs/data/single_pair.json bin/train/inputs/models/demonet.json bin/train/inputs/learning/demo.json bin/train/outputs/MyAmp` from base path.

**Expected behavior**
Training should complete and emit a verified nam.

**Screenshots**
```
$ python bin/train/main.py bin/train/inputs/data/single_pair.json bin/train/inputs/models/demonet.json bin/train/inputs/learning/demo.json bin/train/outputs/MyAmp

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: bin/train/outputs/MyAmp/2023-04-25-21-23-43/lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name | Type    | Params
---------------------------------
0 | _net | WaveNet | 3.0 K
---------------------------------
3.0 K     Trainable params
0         Non-trainable params
3.0 K     Total params
0.012     Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:430: PossibleUserWarning: The dataloader, val_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 9: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 62/62 [00:01<00:00, 47.74it/s, v_num=0]`Trainer.fit` stopped: `max_epochs=10` reached.
Epoch 9: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 62/62 [00:01<00:00, 45.86it/s, v_num=0]
Run (t=9.00)
Traceback (most recent call last):
  File "/workspace/bin/train/main.py", line 224, in <module>
    main(parser.parse_args())
  File "/workspace/bin/train/main.py", line 155, in main
    main_inner(data_config, model_config, learning_config, outdir, args.no_show)
  File "/workspace/bin/train/main.py", line 206, in main_inner
    plot(
  File "/workspace/bin/train/main.py", line 87, in plot
    output = model(*args).flatten().cpu().numpy()
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/nam/models/base.py", line 203, in forward
    return self.net(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/nam/models/_base.py", line 129, in forward
    y = self._forward(x)
  File "/workspace/nam/models/wavenet.py", line 393, in _forward
    y = self._net(x)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/nam/models/wavenet.py", line 300, in forward
    head_input, y = layer(y, x, head_input=head_input)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/nam/models/wavenet.py", line 194, in forward
    x = self._rechannel(x)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```

**Desktop (please complete the following information):**
 - Repro'd on Fedora37 and Ubuntu22.04
 - Running locally
 - `commit 4e97b46cc24417a550d92a82bce2e1d012f10ed5`

**Additional context**
[pip_list.txt](https://github.com/sdatkinson/neural-amp-modeler/files/11361352/pip_list.txt)
[nvidia_smi.txt](https://github.com/sdatkinson/neural-amp-modeler/files/11361354/nvidia_smi.txt)
[training_error.txt](https://github.com/sdatkinson/neural-amp-modeler/files/11361355/training_error.txt)

**Comment by sdatkinson** [comment]
Ah yep, I dealt with this in the Colab and GUI trainers.

I'll grab it today 🙂

**Comment by sprack** [comment]
Just pulled and verified the fix. Thank you!!
