### ISSUE TITLE
[BUG] colab.py, line 40, in _check_for_files     if Path(input_basename).exists(): TypeError: expected str, bytes or os.PathLike object, not tuple

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/neural-amp-modeler#224]
Trying to run the trainer from CLI & getting a tuple error:

(base) PS C:\Users\negru\OneDrive\Desktop\NAM\v0.5.3\neural-amp-modeler-main>
(base) PS C:\Users\negru\OneDrive\Desktop\NAM\v0.5.3\neural-amp-modeler-main> python
Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from nam.train.colab import run
>>> run(1000)
Checking that we have all of the required audio files...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\negru\OneDrive\Desktop\NAM\v0.5.3\neural-amp-modeler-main\nam\train\colab.py", line 89, in run
    input_version, input_basename = _check_for_files()
  File "C:\Users\negru\OneDrive\Desktop\NAM\v0.5.3\neural-amp-modeler-main\nam\train\colab.py", line 40, in _check_for_files
    if Path(input_basename).exists():
  File "C:\Users\negru\anaconda3\lib\pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\negru\anaconda3\lib\pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\negru\anaconda3\lib\pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not tuple
>>>

**Comment by 2-dor** [comment]
Using "v2_0_0.wav" for the reamp

**Comment by sdatkinson** [comment]
Ah I see it. One sec.
