### ISSUE TITLE
[BUG] Running "nam" : Exception in Tkinter callback

### ISSUE THREAD

**Issue by vicpeacock** [sdatkinson/neural-amp-modeler#254]
**Describe the bug**
Throws exception in "Tkinter callback" when training on Mac Pro Intel 12-cores with Monterey 12.6.6
CPU environment successfully created
NAM environment activated

**To Reproduce**
1. Launch nam from shell
2. Fill the information on the GUI
3. Confirm the plot (close the graph)

**Expected behavior**
It should do the training

**Screenshots**
(nam) vincenzopallota@Mac-pro neural-amp-modeler % nam
Now training /Users/vincenzopallota/Music/Documents/Patches/NAM models/Training/Boogie Mark V - Mk1Thick/output.wav
Strong hash: 3b7af089fab0ffbe4492a875776ad467
Provided input file /Users/vincenzopallota/Music/Documents/Patches/NAM models/Training/v1_1_1.wav does not strong-match any known standard input files.
Falling back to weak-matching...
Weak hashes:
 Start:    9f20c6b5f7fef68dd88307625a573a14
 End (v1): 8458126969a3f9d8e19a53554eb1fd52
 End (v2): b63f46673eb738da9c8fca6a274b4edc

Delay wasn't provided; attempting to calibrate automatically...
Delays:
 -6
 -6
After aplying safety factor, final delay is -10
Plotting the delay for manual inspection...
-Checks passed
Starting training. It's time to kick ass and chew bubblegum!
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/vincenzopallota/anaconda3/envs/nam/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/vincenzopallota/Music/Documents/Patches/NAM models/Training/MyCode/neural-amp-modeler/nam/train/gui.py", line 332, in _train
    trained_model = core.train(
                    ^^^^^^^^^^^
  File "/Users/vincenzopallota/Music/Documents/Patches/NAM models/Training/MyCode/neural-amp-modeler/nam/train/core.py", line 738, in train
    trainer = pl.Trainer(
              ^^^^^^^^^^^
  File "/Users/vincenzopallota/anaconda3/envs/nam/lib/python3.11/site-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/vincenzopallota/anaconda3/envs/nam/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 393, in __init__
    self._accelerator_connector = _AcceleratorConnector(
                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vincenzopallota/anaconda3/envs/nam/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 157, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/Users/vincenzopallota/anaconda3/envs/nam/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 386, in _set_parallel_devices_and_init_accelerator
    raise MisconfigurationException(
lightning_fabric.utilities.exceptions.MisconfigurationException: `MPSAccelerator` can not run on your system since the accelerator is not available. The following accelerator(s) is available and can be passed into `accelerator` argument of `Trainer`: ['cpu'].

**Desktop (please complete the following information):**
 - OS [e.g. macOS 12.6.6]
 - Locally run
 
**Additional context**

**Comment by sdatkinson** [comment]
Interesting.

Can you open Python and run the following and let me know what you see?

```python
>>> import torch
>>> torch.backends.mps.is_available()
>>> torch.backends.mps.is_built()
```

Example of what I get on my (Intel) Macbook:

<img width="527" alt="image" src="https://github.com/sdatkinson/neural-amp-modeler/assets/12240186/a2ce9be9-bd24-47a9-b297-8e7e2ea751bb">

**Comment by sdatkinson** [comment]
I'm anticipating the answer will be that we need to modify [the code that checks for MPS](https://github.com/sdatkinson/neural-amp-modeler/blob/d489ef8ad80898d6105b3e13b19195e0cc71e82f/nam/train/core.py#L632) to make sure the answers to _both_ are `True`.

If so, it's a simple fix, so I'm labeling as a good first issue. Great opportunity for a new contributor to get involved 🙂

**Comment by vicpeacock** [comment]
(base) vincenzopallota@Mac-pro ~ % python
Python 3.10.9 (main, Mar  1 2023, 12:33:47) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.backends.mps.is_available()
True
>>> torch.backends.mps.is_built()
True
>>>

**Comment by sdatkinson** [comment]
Very interesting! But you said this is an Intel?

How did you install?

**Comment by sdatkinson** [comment]
On second pass, it seems that `torch.backends.mps.is_available()` should be sufficient according to [the PyTorch docs](https://pytorch.org/docs/stable/notes/mps.html).

So the questions are:
1. Is your Mac _really_ an Intel? (Screencap me the "About This Mac"?)
2. If it is, then how did you manage to fool PyTorch into thinking it was Apple Silicon (if that's synonymous w/ the MPS device being present)?

**Comment by vicpeacock** [comment]
Hi Steve,

I did :

python setup.py build
python setup.py install
conda env create -f environment_cpu.yml
conda activate nam 

![image](https://github.com/sdatkinson/neural-amp-modeler/assets/4801783/bb167901-c534-4e63-82e0-a0aa6dda5309)

I have no idea about PyTorch. I am not using python at all other than installing NAM on this computer.

**Comment by vicpeacock** [comment]
Hi Steve,

UPDATE: 
I reinstalled pytorch and when I  got:

Python 3.10.9 (main, Mar  1 2023, 12:33:47) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.backends.mps.is_available()
False
>>> 

However, after running 
conda env create -f environment_cpu.yml     
conda activate nam 
nam

it gave the same error.

I checked again pytorch and now I get

Python 3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:07:22) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.backends.mps.is_available()
True
>>> torch.backends.mps.is_built()
True
>>> 

As you can see, it installs 3.10.11  while before it was 3.10.9.

Maybe there is some hint here.

Thanks,

    Vincenzo
 
PS: I provide the error message again in case there are some differences than the previous one:

Traceback (most recent call last):
  File "/Users/vincenzopallota/anaconda3/envs/nam/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/vincenzopallota/Music/Documents/Patches/NAM models/Training/MyCode/neural-amp-modeler/nam/train/gui.py", line 336, in _train
    trained_model = core.train(
  File "/Users/vincenzopallota/Music/Documents/Patches/NAM models/Training/MyCode/neural-amp-modeler/nam/train/core.py", line 826, in train
    trainer = pl.Trainer(
  File "/Users/vincenzopallota/anaconda3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
  File "/Users/vincenzopallota/anaconda3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 393, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/Users/vincenzopallota/anaconda3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 157, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/Users/vincenzopallota/anaconda3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 386, in _set_parallel_devices_and_init_accelerator
    raise MisconfigurationException(
lightning_fabric.utilities.exceptions.MisconfigurationException: `MPSAccelerator` can not run on your system since the accelerator is not available. The following accelerator(s) is available and can be passed into `accelerator` argument of `Trainer`: ['cpu'].

**Comment by vicpeacock** [comment]
But I don’t have Apple Silicon. It’s just Intel.

I can do it anyway...

**Comment by vicpeacock** [comment]
Uninstalled Anaconda (including removing the directories)
Re-installed Anaconda
pip install --upgrade neural-amp-modeler

launched nam

Here is what I get when I launch the training:


(base) vincenzopallota@Mac-pro ~ % nam
Now training /Users/vincenzopallota/Music/Documents/Patches/NAM models/Training/Boogie Mark V - Mk1Thick/output.wav
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/vincenzopallota/anaconda3/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/vincenzopallota/anaconda3/lib/python3.10/site-packages/nam/train/gui.py", line 287, in _train
    trained_model = core.train(
  File "/Users/vincenzopallota/anaconda3/lib/python3.10/site-packages/nam/train/core.py", line 377, in train
    input_version = _detect_input_version(input_path)
  File "/Users/vincenzopallota/anaconda3/lib/python3.10/site-packages/nam/train/core.py", line 50, in _detect_input_version
    raise RuntimeError(
RuntimeError: Provided input file /Users/vincenzopallota/Music/Documents/Patches/NAM models/Training/v1_1_1.wav does not match any known standard input files.

Note that I already submitted the files in colab and it worked.

**Comment by vicpeacock** [comment]
Now:

>>> import torch
>>> torch.backends.mps.is_built()
False
>>> torch.backends.mps.is_available()
False
>>>

**Comment by sdatkinson** [comment]
@vicpeacock 

> Now:
> 
> \>\>\> import torch
> \>\>\> torch.backends.mps.is_built()
> \>\>\> False
> \>\>\> torch.backends.mps.is_available()
> \>\>\> False

Ok, this is correct for you...whew! 🎉 

As far as the input not being recognized, you seem to be trying to use a file that's not the same as the `v1_1_1.wav` that you downloaded. Instead, you should use the exact file that you downloaded.

Going to close this Issue since the problem it's about (trying to use MPS even though it's not available on your computer) should be solved for you based on [your reply](https://github.com/sdatkinson/neural-amp-modeler/issues/254#issuecomment-1574798756).
