### ISSUE TITLE
[BUG] CLI Trainer: fp.write(_MAGIC) AttributeError: 'bool' object has no attribute 'write'

### ISSUE THREAD

**Issue by 38github** [sdatkinson/neural-amp-modeler#348]
I am training using the CLI option in a Genesis Cloud instance. It seems to successfully train but when it comes to creating the plot PNG I get the following error:

```
$ python bin/train/main.py bin/train/inputs/data/single_pair.json bin/train/inputs/models/lstm.json bin/train/inputs/learning/default.json bin/train/outputs/MyAmp
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3080') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Missing logger folder: bin/train/outputs/MyAmp/2023-11-21-21-50-20/lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name | Type | Params
------------------------------
0 | _net | LSTM | 5.8 K 
------------------------------
5.8 K     Trainable params
0         Non-trainable params
5.8 K     Total params
0.023     Total estimated model params size (MB)
Epoch 9: 100%|█████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.20it/s, v_num=0]`Trainer.fit` stopped: `max_epochs=10` reached.                                                                         
Epoch 9: 100%|█████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.17it/s, v_num=0]
Run (t=9.00)
Took 6.84 (1.32x)
Run (t=9.00)
Took 6.94 (1.30x)
Traceback (most recent call last):
  File "/home/ubuntu/neural-amp-modeler/bin/train/main.py", line 241, in <module>
    main(parser.parse_args())
  File "/home/ubuntu/neural-amp-modeler/bin/train/main.py", line 163, in main
    main_inner(data_config, model_config, learning_config, outdir, args.no_show)
  File "/home/ubuntu/neural-amp-modeler/bin/train/main.py", line 228, in main_inner
    plot(model, dataset_validation, show=not no_show)
  File "/home/ubuntu/neural-amp-modeler/bin/train/main.py", line 109, in plot
    plt.savefig(savefig)
  File "/usr/local/share/miniconda/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1119, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/usr/local/share/miniconda/lib/python3.9/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/share/miniconda/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
  File "/usr/local/share/miniconda/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/usr/local/share/miniconda/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/usr/local/share/miniconda/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 446, in _print_pil
    mpl.image.imsave(
  File "/usr/local/share/miniconda/lib/python3.9/site-packages/matplotlib/image.py", line 1656, in imsave
    image.save(fname, **pil_kwargs)
  File "/usr/local/share/miniconda/lib/python3.9/site-packages/PIL/Image.py", line 2240, in save
    save_handler(self, fp, filename)
  File "/usr/local/share/miniconda/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 1236, in _save
    fp.write(_MAGIC)
AttributeError: 'bool' object has no attribute 'write'
```
I looked up line 1236 but my lack of Python skills didn't make it better. I use my own fork (and settings) of this repository: https://github.com/38github/neural-amp-modeler/tree/lstm

**Comment by sdatkinson** [comment]
Can you reproduce this using my repo? If this is only a problem on your fork, then I'll have to close it as out-of-scope.

**Comment by 38github** [comment]
> Can you reproduce this using my repo? If this is only a problem on your fork, then I'll have to close it as out-of-scope.

Thank you for the reply. I will try it out as soon as I can and get back to you.

**Comment by sdatkinson** [comment]
Closing this. Go ahead and make a new issue if you come back to this; otherwise, I'll assume it's resolved.
